version: '3.8'

services:
  postgres:
    image: postgres:15  # 固定使用主版本 15 以保证稳定性
    container_name: postgres_prod # 固定名称，便于 docker exec 访问
    environment:
      POSTGRES_USER: postgres # 默认超级用户
      POSTGRES_PASSWORD: postgres # 默认密码
      POSTGRES_DB: userdb # 配置文件中使用的数据库名
    ports:
      - "5432:5432" # Expose for local access; app connects via service name # 宿主机:容器 端口映射
    volumes:
      - /drogon_dev/my-fastest-drogon-app-cpp/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - /data/usershare/PG/pgdata:/var/lib/postgresql/data
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro #:ro以只读方式挂载，避免容器内修改# 模式种子数据
      #- ./pgdata:/var/lib/postgresql/data # 数据持久化，避免容器重启后数据丢失
    restart: unless-stopped # 容器重启策略，除非手动停止# 崩溃/重启时自动重启

  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: drogon_api
  #   depends_on:
  #     - postgres
  #   environment:
  #     # no env needed; config.docker.json baked into image
  #     - TZ=UTC
  #     - JWT_SECRET=mysecretkey
  #   ports:
  #     - "3001:3001"
  #   restart: unless-stopped